title: Creating Slack Apps with Bolt Framework, NodeJS, and APIs
description: >-
    Slack Apps are powerful extensions for Slack, a channel-based messaging platform widely used in the industry like IBM, Amazon, and more. These Apps allow users in a workspace to interact, connect, communicate, and work for efficently. In this 6-week course hosted by Bit Project & Slack, you'll learn how to make your own Slack App using the Bolt Framework, Slack API, Node (JavaScript) and various 3rd Party APIs.
template:
    name: learninglab-template
    repo: your-learninglab-template
before:
    - type: createIssue
      title: Week 1
      body: 1.1-bolt-intro.md
steps:
    - title: 'Week 1: Introduction to Bolt JS'
      description: Learning about Bolt, a framework for creating Slack Apps.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1.2-bots-and-apps.md
          issue: 1
    - title: 'Week 1: Slack Bots vs. Slack Apps'
      description: Learn about the various types of Slack Apps you can make.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1.3-setup-app-and-learn-events.md
          issue: 1
    - title: 'Week 1: Config Setup and Event Listeners'
      description: Setting up a text editor and using event listeners.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1.4-basic-slack-app.md
          issue: 1
    - title: 'Week 1: Creating a Basic Slack App'
      description: Use what you learned and make your first Slack App.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: feedback.md
          issue: 1
    - title: 'Week 1: Feedback'
      description: Provide your feedback for Week 1!
      event: issue_comment.created
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1-complete.md
          issue: 1
        - type: createIssue
          title: Week 2
          body: 2.1-blocks-and-actions.md
        - type: closeIssue
          issue: 1
    - title: 'Week 2: Block Kits and Actions'
      description: Introduction to BlockKits and Actions in the Slack API.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 2.2-blocks-and-actions-app.md
          issue: 6
    - title: 'Week 2: Building an App with Block Kits and Actions '
      description: Use BlockKits and Actions to make a Slack App.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 2.3-commands-and-modals.md
          issue: 6
    - title: 'Week 2: Commands and Modals'
      description: Introduction to Commands and Modals in the Slack API.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 2.4-time-converter.md
          issue: 6
    - title: 'Week 2: Time Converter Slack App'
      description: Use what you learned to create a Time Converter Slack App.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: feedback.md
          issue: 6
    - title: 'Week 2: Feedback'
      description: Provide your feedback for Week 2!
      event: issue_comment.created
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 2-complete.md
          issue: 6
        - type: createIssue
          title: Week 3
          body: 3.1-reaction-event-listener-and-threads.md
        - type: closeIssue
          issue: 6
    - title: 'Week 3: Google Translate API: Event Listener & Threads'
      description: Introduction to a new event listener and responding in threads.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 3.2-oauth-account-and-credentials.md
          issue: 11
    - title: 'Week 3: Google Translate API: Account & Credentials'
      description: Setting up a Google Developer Account and using the Translator.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 3.3-calling-translator-api.md
          issue: 11
    - title: 'Week 3: Google Translate API: Calling the Translator'
      description: Integrating the Translator in a Slack App.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: feedback.md
          issue: 11
    - title: 'Week 3: Feedback'
      description: Provide your feedback for Week 3!
      event: issue_comment.created
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 3-complete.md
          issue: 11
        - type: createIssue
          title: Week 4
          body: 4.1-express.md
        - type: closeIssue
          issue: 11
    - title: 'Week 4: Introduction to Express'
      description: Learn about ExpressJS and what it can do.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 4.2-webhooks.md
          issue: 15
    - title: 'Week 4: Introduction to Webhooks'
      description: Learn about what webhooks are and how to use them in a Slack App.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 4.3-final-project.md
          issue: 15
    - title: 'Week 4: Final Project with Github API'
      description: Finish up the course by creating your last Slack App with the Github API.
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: feedback.md
          issue: 15
    - title: 'Week 4: Feedback'
      description: Provide your feedback for Week 4!
      event: issue_comment.created
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 4-complete.md
          issue: 15
        - type: closeIssue
          issue: 15
